language: java
jdk:
- oraclejdk8

before_install:
- "./src/main/scripts/ci/before-install.sh"
  after_success:
  - java -jar ~/codacy-coverage-reporter-assembly.jar -l Java -r ./target/site/jacoco/jacoco.xml
script:
- mvn -version
before_deploy:
- git checkout $TRAVIS_BRANCH
deploy:
- provider: script
  script: mvn -P release deploy -DskipTests=true -B -V -s travis-settings.xml
  on:
    branch: develop
- provider: script
  script:
    - "./src/main/scripts/cd/deploy.sh"
  on:
    branch: master
